export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOADED_ERROR = 'USER_LOADED_ERROR';
export const USER_LOG_OUT = 'USER_LOG_OUT';

//UPDATE TYPES::
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

//ADD DETIALS
export const REQUEST_CHECK_USER = 'REQUEST_CHECK_USER';
export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const ADD_USER_DETAILS_ERROR = 'ADD_USER_DETAILS_ERROR';
export const ADD_USER_NUMBER = 'ADD_USER_NUMBER';
//Register Types:
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

//Login Types::
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';

//Category TYPES::
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_ERROR = 'GET_ALL_CATEGORIES_ERROR';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_FILTER_ACTIVE_CATEGORY = 'SET_FILTER_ACTIVE_CATEGORY';

//PRODUCTS TYPES:
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';

//export const
export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR';

//CART TYPES:
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';

//Ref Types::
export const ADD_BOTTOM_REF = 'ADD_BOTTOM_REF';
export const ADD_MOBILE_REF = 'ADD_MOBILE_REF';
export const ADD_OTP_REF = 'ADD_OTP_REF';
export const ADD_LOGIN_OTP_REF = 'ADD_LOGIN_OTP_REF';
export const ADD_REGISTER_OTP_REF = 'ADD_REGISTER_OTP_REF';
export const ADD_REGISTER_SHEET_REF = 'ADD_REGISTER_SHEET_REF';

//Delivery Address Types::
export const GET_DELIVERY_ADDRESS_SUCCESS = 'GET_DELIVERY_ADDRESS_SUCCESS';
export const GET_DELIVERY_ADDRESS_ERROR = 'GET_DELIVERY_ADDRESS_ERROR';

//ADDING
export const ADD_DELIVERY_ADDRESS_REQUEST = 'ADD_DELIVERY_ADDRESS_REQUEST';
export const ADD_DELIVERY_ADDRESS_SUCCESS = 'ADD_DELIVERY_ADDRESS_SUCCESS';
export const ADD_DELIVERY_ADDRESS_ERROR = 'ADD_DELIVERY_ADDRESS_ERROR';
export const DELETE_DELIVERY_ADDRESS_SUCCESS =
  'DELETE_DELIVERY_ADDRESS_SUCCESS';

export const SET_ACTIVE_ADDRESS = 'SET_ACTIVE_ADDRESS';

//OTP TYPES::
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_ERROR = 'SEND_OTP_ERROR';

//
export const SET_LOGIN_OTP_REF = 'SET_LOGIN_OTP_REF';

//Search Types:::::::::::
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';
export const SET_QUERY = 'SET_QUERY';

//RATINGS::
export const ADD_RATING_REQUEST = 'ADD_RATING_REQUEST';
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS';
export const ADD_RATING_ERROR = 'ADD_RATING_ERROR';

//ORDER TYPES::::
export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

//MAIN OFFERS TYPES::
export const GET_MAIN_OFFER_SUCCESS = 'GET_MAIN_OFFER_SUCCESS';
export const GET_MAIN_OFFER_ERROR = 'GET_MAIN_OFFER_ERROR';

//
export const EMPTY_CART = 'EMPTY_CART';

//Filter Types::
export const FILTER_PRODUCT = 'FILTER_PRODUCT';

//CHECK INVENTORY
export const CHECK_INVENTORY_REQUEST = 'CHECK_INVENTORY_REQUEST';
export const CHECK_INVENTORY_SUCCESS = 'CHECK_INVENTORY_SUCCESS';
export const CHECK_INVENTORY_ERROR = 'CHECK_INVENTORY_ERROR';

//LIVE ORDER TYPES::
export const GET_LIVE_ORDER_REQUEST = 'GET_LIVE_ORDER_REQUEST';
export const GET_LIVE_ORDER_SUCCESS = 'GET_LIVE_ORDER_SUCCESS';
export const GET_LIVE_ORDER_ERROR = 'GET_LIVE_ORDER_ERROR';

//PAST ORDER TYPES::
export const GET_PAST_ORDER_REQUEST = 'GET_PAST_ORDER_REQUEST';
export const GET_PAST_ORDER_SUCCESS = 'GET_PAST_ORDER_SUCCESS';
export const GET_PAST_ORDER_ERROR = 'GET_PAST_ORDER_ERROR';

//SINGLE ORDER TYPES::
export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_ERROR = 'GET_ORDER_DETAILS_ERROR';
